### PR TITLE
add correct none check to distortion params

### PR DESCRIPTION
**Pull request by nikmo33**
If distortion params are provided and not None, then this check fails with 
`RuntimeError: Boolean value of Tensor with more than one value is ambiguous`

### CODE REVIEW

**Comment by nikmo33** [comment]
ns-dev-test

**Review by tancik — APPROVED** [review]
LGTM. Thanks for the PR!

**Comment by tancik** [comment]
Can you run `ns-dev-test` to fix the formatting errors

**Comment by nikmo33** [comment]
> Can you run `ns-dev-test` to fix the formatting errors

Thanks! Done!

**Pull request merged**
