### PR TITLE
Fix bug related to distributed data parallel training

### PR DESCRIPTION
**Pull request by jb-ye**
Address issue #1847

### CODE REVIEW

**Comment by tancik** [comment]
If you run `ns-dev-test` it will fix the black errors. (Install the dev dependencies with `pip install -e .[dev]`)

**Comment by ethanweber** [comment]
Hi @jb-ye, I'm not seeing a change when I run it on my end with 1 vs. 4 GPUs. I'm including the main branch in this plot as well. Do you see something differently? If so, could you share with us? Here I'm running `ns-train mipnerf --data data/blender/lego --machine.num-gpus 4 --vis wandb blender-data` vs `ns-train mipnerf --data data/blender/lego --machine.num-gpus 1 --vis wandb blender-data`.

image

**Comment by jb-ye** [comment]
@ethanweber I realized you are plotting against loss vs. training time. My local experiment shows that the benefits of parallel saturate at two GPUs for most of my experiments. Because 4 GPUs, the communication overhead is too much.

**Comment by jb-ye** [comment]
@tancik Do you expect to merge this change?

**Comment by ethanweber** [comment]
Should [this line](https://github.com/nerfstudio-project/nerfstudio/blob/2f02479a2679c3212233bf9e2d9623766cbcab2c/nerfstudio/pipelines/base_pipeline.py#L142) be changed too? I don't think it's called anywhere right now but seems like the same issue. Before you merge, could you add an example in the docs along with vanilla nerf that uses nerfacto and trains faster with multiple GPUs? I think it would be great to get more nerfacto uses using multi GPU if it's working now.

**Comment by jb-ye** [comment]
> Should [this line](https://github.com/nerfstudio-project/nerfstudio/blob/2f02479a2679c3212233bf9e2d9623766cbcab2c/nerfstudio/pipelines/base_pipeline.py#L142) be changed too? I don't think it's called anywhere right now but seems like the same issue. Before you merge, could you add an example command in the docs along with vanilla nerf that uses nerfacto and trains faster with multiple GPUs? I think it would be great to get more nerfacto uses using multi GPU if it's working now.

I noticed this line as well, but for class Pipeline, self._model is never instantiated in its constructor. So I thought it doesn't have self._model and doesn't support multi-gpu by design.

**Review by ethanweber — COMMENTED** [review]
I just made these changes, and I think things look good to go! Thanks for the PR and documenting it!

**Comment by jb-ye** [comment]
Looks good to me!

**Review by ethanweber — APPROVED** [review]

**Pull request merged**
