### PR TITLE
Use ruff as linter and formatter

### PR DESCRIPTION
**Pull request by ringohoffman**
Alternative to #2754 based on @brentyi's suggestion: https://github.com/nerfstudio-project/nerfstudio/pull/2754#issuecomment-1890082170

Upgrade `ruff` and use `ruff format ...` as a drop in replacement for `black`: https://docs.astral.sh/ruff/formatter/

Also use `ruff check ... --fix` as a drop in replacement for `isort` (produces identical results as using the following `isort` config):

```toml
[tool.isort]
combine_as_imports = true
line_length = 120
known_first_party = ["nerfstudio"]
profile = "black"
```

Update `pre-commit` hooks, VS Code `settings.json`, and CI steps.

BTW you may need to run `pre-commit autoupdate` or clear your cache in order to start using the new `ruff` hooks.

### CODE REVIEW

**Comment by ringohoffman** [comment]
I was worried that the `ruff-format` `pre-commit` hook somehow missed the files in my last commit, but I think `ruff check` and `ruff format` just happened to affect 2 mutually exclusive groups of files.

**Comment by brentyi** [comment]
Looks good to me! @tancik any opposition to moving away from `black`?

**Comment by tancik** [comment]
None from me

**Review by brentyi — APPROVED** [review]

**Comment by brentyi** [comment]
Thanks @ringohoffman!!

**Pull request merged**
