### PR TITLE
Fix pillow version to avoid error with ANTIALIAS (Fix #2378)

### LINKED ISSUE #2378: Reference to ANTIALIAS in PIL
**Describe the bug**
When running the docker image 

The process data script fails to load the pixel-perfect extractor

**To Reproduce**
1. Run through the docs - when running the interactive docker container
```docker run --gpus all  -u 1000 -v /home/mdcurrent/Videos:/workspace/  -v /home/mdcurrent/.cache/:/home/user/.cache/  -p 7007:7007 --rm -it --shm-size=12gb  nerfstudio-89```

see the error 
```❌ Completion script generation failed: ['ns-process-data', '--tyro-print-completion', 'bash'] install.py:124
           Traceback (most recent call last):                                                             install.py:128
             File "/usr/local/bin/ns-process-data", line 5, in <module>                                                 
               from nerfstudio.scripts.process_data import entrypoint                                                   
             File "/home/user/nerfstudio/nerfstudio/scripts/process_data.py", line 36, in <module>                      
               from nerfstudio.process_data.colmap_converter_to_nerfstudio_dataset import                               
           BaseConverterToNerfstudioDataset                                                                             
             File                                                                                                       
           "/home/user/nerfstudio/nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py",                   
           line 21, in <module>                                                                                         
               from nerfstudio.process_data import colmap_utils, hloc_utils, process_data_utils                         
             File "/home/user/nerfstudio/nerfstudio/process_data/hloc_utils.py", line 45, in <module>                   
               from pixsfm.refine_hloc import PixSfM  # type: ignore                                                    
             File "/home/user/pixel-perfect-sfm/pixsfm/__init__.py", line 19, in <module>                               
               from . import (  # noqa F403                                                                             
             File "/home/user/pixel-perfect-sfm/pixsfm/features/__init__.py", line 2, in <module>                       
               from . import models, extractor, extract_patches, store_features, store_references  # noqa               
           F403                                                                                                         
             File "/home/user/pixel-perfect-sfm/pixsfm/features/extractor.py", line 32, in <module>                     
               class FeatureExtractor:                                                                                  
             File "/home/user/pixel-perfect-sfm/pixsfm/features/extractor.py", line 64, in                              
           FeatureExtractor                                                                                             
               filters = {                                                                                              
             File "/home/user/pixel-perfect-sfm/pixsfm/features/extractor.py", line 65, in <dictcomp>                   
               n: getattr(PIL.Image, n)                                                                                 
           AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'  
```

**Expected behavior**
Haven't gotten a clean run, but expect the docker container to boot and not die instantly

**Screenshots**
Screenshot from 2023-08-28 22-07-12

**Additional context**
i could be missing something but i think i set the right 8.9/ 89 everywhere applicable and updated nvidia drivers / a clean build

Looks like the attribute has been sunset 
https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants

TIA!

### PR DESCRIPTION
**Pull request by ahmed-shariff**
Fix pillow version to avoid error with ANTIALIAS (Fix #2378)

### CODE REVIEW

**Comment by brentyi** [comment]
Can we fix this upstream in `pixsfm` instead? https://github.com/cvg/pixel-perfect-sfm/issues/119

**Comment by brentyi** [comment]
Thanks for the PR! Does it make sense to fix this upstream in `pixsfm` instead? https://github.com/cvg/pixel-perfect-sfm/issues/119

**Comment by ahmed-shariff** [comment]
That is probably a better solution 😅 
I'll leave this open until that gets fixed.

**Comment by ahmed-shariff** [comment]
@brentyi it has been fixed upstream. I am reverting the version change and updating the docker to use the latest commit as opposed to the tag.

**Review by MDCurrent — COMMENTED** [review]
TYSM!

**Review by brentyi — APPROVED** [review]

**Pull request merged**
