### PR TITLE
nerfstudio dataparser: avoid loading images at inference time

### PR DESCRIPTION
**Pull request by f-dy**
Also remove the image skipping logic, which seems to be a remnant of some old code (all images should exist).
This allows running inference (s-render or ns-export) without the images.
Fixes https://github.com/nerfstudio-project/nerfstudio/issues/2050

### CODE REVIEW

**Comment by tancik** [comment]
I'm a bit confused, I don't see how these changes solves the issue.

**Comment by f-dy** [comment]
if the downscalefactore is None, _get_fname tries to open the image to compute it from the image resolution, here  https://github.com/nerfstudio-project/nerfstudio/blob/5511f5f4edf45a163a19ce2ff41e8b5fe2b9771e/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#L322

**Comment by f-dy** [comment]
and this check for file existence here https://github.com/nerfstudio-project/nerfstudio/blob/5511f5f4edf45a163a19ce2ff41e8b5fe2b9771e/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#L112

I don't think it's any useful. all images should be available for training anyway

**Review by tancik — APPROVED** [review]
LGTM

**Comment by pwais** [comment]
@f-dy this had been bugging me for a while, thank you so much for fixing!! 🎉

**Pull request merged**
