### PR TITLE
Update host address

### LINKED ISSUE #1735: Blank viewer
When I run nerfstudio on linux and open the viewer, I don't see the input image, just a blank coordinate system,please tell me why.
I can see training progress in the terminal。

### PR DESCRIPTION
**Pull request by tancik**
Switching host to`127.0.0.1`.

Fixes #1735

### CODE REVIEW

**Review by brentyi — APPROVED** [review]
Looks fine to me, but FYI it won't change functionality given #1759

**Comment by machenmusik** [comment]
Note that 0.0.0.0 introduces potential security exposure (i.e. if the server is going to bind to all by default, that should be clarified in documentation with bang warning signs), so if the intent is to keep local loop only, definitely prefer 127.0.0.1 !
-------- Original message --------From: Matthew Tancik ***@***.***> Date: 4/18/23  3:05 PM  (GMT-08:00) To: nerfstudio-project/nerfstudio ***@***.***> Cc: Subscribed ***@***.***> Subject: [nerfstudio-project/nerfstudio] Update host address (PR #1766) Not sure if it is better to set to 0.0.0.0 or 127.0.0.1.
Fixes #1735



You can view, comment on, or merge this pull request online at:
  https://github.com/nerfstudio-project/nerfstudio/pull/1766

Commit Summary

  fbb51ff  Update host address


File Changes  (1 file)

  
    M
    nerfstudio/viewer/viser/server.py
    (2)
  


Patch Links:

  https://github.com/nerfstudio-project/nerfstudio/pull/1766.patch
  https://github.com/nerfstudio-project/nerfstudio/pull/1766.diff

**Comment by brentyi** [comment]
@tancik I think 127.0.0.1 as merged will re-break Colab / #1735 

If we're worried about security (which is reasonable), the host could be exposed in the config?

**Comment by tancik** [comment]
127.0.0.1 appears to still work in colab.

**Pull request merged**
