### PR TITLE
Fix get_num_frames_in_video

### PR DESCRIPTION
**Pull request by olegpokhilchenko**
Tests have shown that there can be 2 exact same numbers in the output, separated by non-digit symbols. I think it's better to just find the first number.

### CODE REVIEW

**Comment by tancik** [comment]
What are you seeing as the output of ffmpeg? I wan't to get a better idea about when it fails.

**Comment by olegpokhilchenko** [comment]
Yes, in some cases ffprobe can give results like this: 123123\n\n123123.
For example, the AVCHD codec in MTS format does this.

**Comment by tancik** [comment]
This doesn't work for me. I ran a test where it should return 635 frames, but it only returned 6.

**Comment by olegpokhilchenko** [comment]
There was an error in the code: `output[0]` was referencing the initial command output, which is not what we want. I changed it to `number_match[0]`. This means "take the regex match and return the group 0 of it (whole match)".

**Pull request merged**
