### PR TITLE
Refactor splatfacto gaussian params with a ParameterDict

### PR DESCRIPTION
**Pull request by kerrj**
This simplifies subclassing, and simplifies some of the logic for culling/splitting.

### CODE REVIEW

**Comment by jb-ye** [comment]
The change looks good to me. Some suggestions:

(1) test PLY exporter end-to-end to safeguard the workflow is fine.
(2) since the change disallow loading checkpoint from previous versions. I would suggest we bump a major version number like (1.1.0) to distinguish from previous versions. User can still use earlier versions to view their assets.

**Comment by jb-ye** [comment]
One more thing: when rebasing on top of https://github.com/nerfstudio-project/nerfstudio/pull/2945 We need to change the parameter names for splatfacto-big.

**Comment by kerrj** [comment]
This should be ready to merge, fixed all the mentioned changes and also added loading logic to make it backwards-compatible with old checkpoints.

**Comment by maturk** [comment]
LGTM! Can we merge this?

**Pull request merged**
