### PR TITLE
Update to allow pytorch (and functorch) 1.13.1

### PR DESCRIPTION
**Pull request by machenmusik**
Note that for existing installations, the following is recommended due to complications with older versions of functorch:
- `pip uninstall torch torchvision functorch`
- install the correct pytorch 1.13.1 version for your CUDA installation from https://pytorch.org/get-started/locally/ but add functorch to the command -- for example, CUDA 11.7 would be `pip3 install torch torchvision functorch --extra-index-url https://download.pytorch.org/whl/cu117`
- reinstall tinycudann torch bindings e.g. `pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`
- reinstall nerfstudio e.g. `pip install -e .` from the source directory

### CODE REVIEW

**Comment by machenmusik** [comment]
(Need corresponding updates to docs.)

**Review by tancik — APPROVED** [review]
LGTM

**Comment by machenmusik** [comment]
(Not sure what the readthedocs failure is from, the details link goes to 404)

**Comment by tancik** [comment]
> (Not sure what the readthedocs failure is from, the details link goes to 404)

The error is 
`/home/docs/checkouts/readthedocs.org/user_builds/plenoptix-nerfstudio/checkouts/1390/docs/quickstart/installation.md:162: WARNING: 'myst' reference target not found: #pytorch`

**Comment by machenmusik** [comment]
Thx - weird, because it is a local anchor reference that works fine e.g.
https://github.com/nerfstudio-project/nerfstudio/blob/d0fe3677a460a1e467f2765c7842b16a0b2ea15f/docs/quickstart/installation.md#pytorch

**Comment by tancik** [comment]
You can run `python scripts/docs/build_docs.py --clean-cache` to see the error locally.
If you add `(pytorch)=` at line 20 and remove the `#`, it should work.

**Comment by machenmusik** [comment]
Ok, although that breaks usage of the MD files as-is on github.

**Pull request merged**
