### PR TITLE
Fix IndexError runtime error

### PR DESCRIPTION
**Pull request by machenmusik**
fixes this error:

  File "C:\code\nerfstudio\nerfstudio\data\dataparsers\nerfstudio_dataparser.py", line 232, in _generate_dataparser_outputs
    distortion_params = torch.stack(distort, dim=0)[idx_tensor]
IndexError: tensors used as indices must be long, byte or bool tensors

### CODE REVIEW

**Review by tancik — APPROVED** [review]
LGTM

**Comment by machenmusik** [comment]
(Apologies for the force push; attribution was messed up, same one-liner change.)

**Comment by tancik** [comment]
Do you think it would be better to just update line 215 with
`idx_tensor = torch.tensor(indices, dtype=torch.long)`
?

**Comment by machenmusik** [comment]
That, or the variation in https://github.com/nerfstudio-project/nerfstudio/pull/1055#issuecomment-1332630814, would presumably work as well, is there a preference?  Happy to change the one-liner if so (and to do corresponding PR to realitycapture branch if needed)

**Comment by tancik** [comment]
I think just the single edit would be good

**Pull request merged**
