### PR TITLE
Render in threejs viewer

### PR DESCRIPTION
**Pull request by machenmusik**
Bring the background image under threejs control in the ViewerWindow.

### CODE REVIEW

**Comment by machenmusik** [comment]
(Perhaps more important than threejs niceties: after this change, the viewer including background is encapsulated in a single React element, which should be simpler to modify/replace.)

**Comment by tancik** [comment]
This looks fine to me. I'm curious, how does this impact performance?

**Comment by machenmusik** [comment]
From my light tests, negligible so far.

**Review by tancik — APPROVED** [review]
LGTM

**Pull request merged**
