### PR TITLE
Fix arguments that are not passed from config to NerfactoField

### PR DESCRIPTION
**Pull request by liu115**
Models like `nerfacto-big` and `nerfacto-huge` are changing `base_res` and `features_per_level` in the config. However, the arguments are not actually passed to NerfactoField currently.

### CODE REVIEW

**Comment by tancik** [comment]
Good find! I think it makes sense to reset the nerfacto-big and huge configs so that the performance doesn't change (Im mostly worried about GPU memory). Later we can retune these values now that we know they will actually do something :)

**Comment by liu115** [comment]
@tancik Thanks! Should I then update the configs and add it in this PR?

**Comment by tancik** [comment]
That would be great!

**Review by tancik — APPROVED** [review]
Lgtm

**Pull request merged**
