### PR TITLE
fix_mask

### PR DESCRIPTION
**Pull request by Tao-11-chen**
Using masks to avoid sampling pixels on masked areas take times, so we should put masks to CUDA.
But this can lead to using indices on CUDA to query image pixels on CPU. 
Instead of putting all the images to CUDA, transform the indices tensor to CPU is more efficient.

### CODE REVIEW

**Comment by Tao-11-chen** [comment]
If it is right, should revert #1741 before merging.

**Comment by Tao-11-chen** [comment]
In no case should all the images put to GPU cus masks are often used to deal with dynamic objects of outdoor scenes. These scenes are usually big and contain large images.

**Comment by nepfaff** [comment]
Could you produce some results comparing this approach's training speed and memory consumption compared to https://github.com/nerfstudio-project/nerfstudio/pull/1741? Let me know if you need a small dataset with masks.

**Comment by Tao-11-chen** [comment]
You could refer to #1747 for speed test and analysis. I'll give a more detailed result later.

**Comment by machenmusik** [comment]
It would help if we could make available a larger dataset with masks for which this PR is tailored, so we could run some comparisons.

We should be able to determine size of images / datasets, if we have to choose behavior accordingly...

**Comment by machenmusik** [comment]
So far, with https://github.com/machenmusik/nerfstudio/tree/mask2 which includes reverting #1741, I am seeing similar results with small `mustard` dataset using nerfacto, and perhaps some small improvement since not uploading images.  @nepfaff I believe you were using instant-ngp, can you confirm similar results?

**Comment by machenmusik** [comment]
> On a side note, we would not want to revert all of https://github.com/nerfstudio-project/nerfstudio/pull/1741 as it also added masking capability to the instant-npg dataparser. I added them in the same PR as masks were broken, so adding them to a dataparser without fixing them did not make sense.

@nepfaff perhaps you can craft a PR that only reverts the images-to-GPU portion of #1741, so we can merge, and then merge this?

**Comment by Tao-11-chen** [comment]
Thanks very much for testing it, glad to hear that it makes scense. In my situation, putting all the images to GPU causes OOM on RTX3090 untill i set image_batch_size to less than 100 out of 4000, which makes training slow with much of the time spent on I/O.

**Review by machenmusik — APPROVED** [review]
Thanks!

**Pull request merged**
