### PR TITLE
Fixes bug in PairPixelSampler when working with masked dataset

### PR DESCRIPTION
**Pull request by padeler**
PairPixelSampler does not compute the correct indices when there are masks in the dataset. This fixes the issue.

### CODE REVIEW

**Comment by tancik** [comment]
Can you run `ns-dev-test`

**Comment by elenacliu** [comment]
sry to bother you, but can you explain what the bug is?

**Comment by padeler** [comment]
> sry to bother you, but can you explain what the bug is?

Basically its an indentation error in the else block. 

The  sample_method is supposed to select ray pairs by first randomly selecting half the rays and then picking the other half from a radius near the first ones. 

In the code when a mask is available it was selecting the indices for the first half but did not select their pairs.

**Review by AdamRashid96 — APPROVED** [review]
LGTM

**Pull request merged**
