### PR TITLE
Ply dataparser

### PR DESCRIPTION
**Pull request by CardiacMangoes**
IN PROGRESS do not merge yet

Loads a ply file as initial point cloud if specified

Specify `transforms.json` with "ply_file_path" in header, i.e

{
    "camera_model": "OPENCV",
    "cx": 320,
    "cy": 240,
    "w": 640,
    "h": 480,
    "ply_file_path": "smith.ply",
    ...

### CODE REVIEW

**Comment by ethanweber** [comment]
Nice, this is useful. I think we can merge the dataparser with its own PR, and then a separate PR should add code to ns-process-data to generate a PLY from colmap when it finishes.

**Comment by kerrj** [comment]
I think this is useful enough to merge into main, since it includes generally loading .ply files in the dataparser and also metric export option

**Comment by kerrj** [comment]
Need to pull out just the relevant changes though, changing the base branch includes all of splatting too

**Review by kerrj — APPROVED** [review]
sgtm

**Pull request merged**
