### PR TITLE
Wandb/experiment improvements

### PR DESCRIPTION
**Pull request by ethanweber**
This PR fixes a consistent ordering for eval images when using a random seed. It also gives functionality for setting the wandb project name, setting the experiment name, and loading from a checkpoint path.

### CODE REVIEW

**Comment by jkulhanek** [comment]
So wandb environment variables are no longer supported? 
https://docs.wandb.ai/guides/track/environment-variables

**Comment by ethanweber** [comment]
@jkulhanek I'll fix that right now!

**Comment by ethanweber** [comment]
If you want to double check at PR #1880, that would be great. Thanks!

**Comment by Tao-11-chen** [comment]
Hi, I'm suffering from getting Null metrics_dict while the training step reached get_average_eval_image_metrics at the second time after this change.

**Comment by ethanweber** [comment]
Thanks for fixing it!

**Pull request merged**
