### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by erich666**
Everyone's fixing them, but I still see a few. Here you go.

The commas after "e.g." are [the norm in American English](https://jakubmarian.com/comma-after-i-e-and-e-g/#:~:text=Virtually%20all%20American%20style%20guides,motherboards%2C%20graphic%20cards%2C%20CPUs.).

NOTE: on line 169 is "please visit our viewer [walk-through]()" - I could not figure out if there's a place you wanted to point the user. Future work?

### CODE REVIEW

**Review by tancik — APPROVED** [review]

**Comment by tancik** [comment]
The link should be https://docs.nerf.studio/en/latest/quickstart/viewer_quickstart.html

**Comment by ethanweber** [comment]
Thanks @erich666!

**Comment by erich666** [comment]
> The link should be https://docs.nerf.studio/en/latest/quickstart/viewer_quickstart.html

Thanks, and I leave it to you to add this in.

**Comment by ethanweber** [comment]
> > The link should be https://docs.nerf.studio/en/latest/quickstart/viewer_quickstart.html
> 
> Thanks, and I leave it to you to add this in.

Awesome, I'll go ahead and merge then. Thanks.

**Pull request merged**
