### PR TITLE
feat(ci): migrate to `uv` in CI

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
This PR aims to migrate the python dependency installation to [uv](https://github.com/astral-sh/uv) from pip. [uv](https://github.com/astral-sh/uv) backed by [Astral](https://astral.sh/), the creators of [Ruff](https://github.com/astral-sh/ruff), is an extremely fast Python package installer and resolver, written in Rust. According to their open-source benchmarks they are [10-100x faster](https://github.com/astral-sh/uv/blob/main/BENCHMARKS.md) than pip and pip-tools (pip-compile and pip-sync).

### CODE REVIEW

**Comment by jb-ye** [comment]
It looks like an attractive PR: it reduces "install dependencies" step from 3m to 40 seconds. @tancik @brentyi  Let me know what do you think? 

@SauravMaheshkar Could you help also incorporate uv to this doc workflow? https://github.com/nerfstudio-project/nerfstudio/blob/main/.github/workflows/doc.yml

**Comment by SauravMaheshkar** [comment]
> It looks like an attractive PR: it reduces "install dependencies" step from 3m to 40 seconds. @tancik @brentyi Let me know what do you think?
> 
> @SauravMaheshkar Could you help also incorporate uv to this doc workflow? https://github.com/nerfstudio-project/nerfstudio/blob/main/.github/workflows/doc.yml

Yup updating the doc workflow 😄

**Comment by brentyi** [comment]
Moving to `uv` sounds good to me.

One question: the changes also add a virtual environment, is this necessary in the CI?

**Comment by SauravMaheshkar** [comment]
> Moving to `uv` sounds good to me.
> 
> One question: the changes also add a virtual environment, is this necessary in the CI?

Hello 👋🏽 , Yes it's necessary for `uv` to function. [Necessary information can be found in the docs](https://github.com/astral-sh/uv?tab=readme-ov-file#python-discovery)

**Comment by SauravMaheshkar** [comment]
I'd suggest a Squash Merge.

**Review by brentyi — APPROVED** [review]
I was able to remove the virtual environment by passing a `--system` flag to `uv pip`.

Seems like this will be a great quality-of-life improvement, thanks @SauravMaheshkar for making the PR and @jb-ye for bumping!

**Pull request merged**
