### PR TITLE
Support splatfacto training for metashape exports

### PR DESCRIPTION
**Pull request by jb-ye**
test commands:

```
ns-process-data metashape --xml floorboard.xml --data floorboard/ --ply floorboard.ply --output-dir floorboard_nerfstudio/
```

### CODE REVIEW

**Comment by jb-ye** [comment]
@simonbethke Could you try this PR and see if it works? I manually tested your dataset, and it seems fine.

**Comment by simonbethke** [comment]
Yea, I will test it

**Comment by simonbethke** [comment]
Okay, i tested a little bit. The happy path works!!

The unhappy paths are rather bad. Not worse than the average quality but when taking that as benchmark it will stay bad forever :D

1) When the ply-file has not .ply extension a stacktrace is printed. As this case is handled and even has a message, it should not print the stacktrace
2) when providing a non-existing .ply file, it takes forever, then there are some Open3D warnings and in the end, it summarizes that it imported the non-existing file which is wrong.

**Comment by simonbethke** [comment]
I know handling unhappy paths is tideous and no fun. If you like, just ignore what I wrote about them.

**Comment by brentyi** [comment]
For the stack trace verbosity, maybe we can add `ValueError` to the `try`/`except` statement?

https://github.com/nerfstudio-project/nerfstudio/blob/41deed6a52a33996b34053eea58bdc54e714573f/nerfstudio/scripts/process_data.py#L531C1-L539C1

**Comment by jb-ye** [comment]
> For the stack trace verbosity, maybe we can add `ValueError` to the `try`/`except` statement?
> 
> https://github.com/nerfstudio-project/nerfstudio/blob/41deed6a52a33996b34053eea58bdc54e714573f/nerfstudio/scripts/process_data.py#L531C1-L539C1

Yes, I sent out a new revision.

**Review by brentyi — APPROVED** [review]
Looks good to me, thanks @simonbethke @jb-ye!

**Comment by simonbethke** [comment]
Thank you both for your help!

**Comment by simonbethke** [comment]
Regarding this PR:
unfortunately there is still a gap. If I transform something in metashape, the data cannot be exported/imported to nerfstudio anymore. I think the reason for this is, that in the metashape xml, another transform appears that is not used in the nerfstudio importer. However, I already tried to get this working but I was not able to. 
I have to provide sample data for that and it would be great if somebody could look into this :)

**Comment by jb-ye** [comment]
@simonbethke Could you start a new issue and provide sample data there?

**Pull request merged**
