### PR TITLE
export gaussian splats reconstruction as PLY

### PR DESCRIPTION
**Pull request by cdcseacave**
Export a checkpoint trained with gaussian splatting in nerfstudio to a PLY file compatible with the original format. For example it can be visualized at `https://antimatter15.com/splat/` by simply drag&drop the ply on the browser window.

[Video.webm](https://github.com/nerfstudio-project/nerfstudio/assets/2802670/cfabc940-f1ee-453d-980d-d40e98e20a83)

### CODE REVIEW

**Comment by maturk** [comment]
There are now two PRs for this, ref #2535. Can these be combined?

**Comment by cdcseacave** [comment]
That one does not work, i had to reimplement

**Comment by machenmusik** [comment]
I can confirm this works.  Although initial orientation from drag-n-drop onto this page is not as expected; this is after rotations etc.  
Will also try the other one...
image

**Comment by machenmusik** [comment]
> That one does not work, i had to reimplement
> […](#)
> On Tue, Oct 17, 2023 at 15:47 Matias Turkulainen ***@***.***> wrote: There are now two PRs for this, ref #2535 <#2535>. Can these be combined?

See discussion on https://github.com/nerfstudio-project/nerfstudio/pull/2535; it does work if spherical harmonics are present in the output to be exported, but fails if they are not.

**Comment by kerrj** [comment]
Given the other PR was merged and it seems to support both RGB only and SH, can we close this one? @machenmusik @cdcseacave

**Pull request closed without merging**
