### PR TITLE
made Dockerfile singularity/apptainer compatible

### LINKED ISSUE #2952: Docker/singularity container doesn't seem to contain ns-* commands
**Describe the bug**

I built a singularity container from the Dockerhub address listed on the web page and then ran "singularity run --nv nerf.simg" and tried to find the ns-* files but I am unable to find them. 

**To Reproduce**

Run:  

singularity build nerf.simg docker://dromni/nerfstudio:1.0.2

singularity run --nv nerf.sif ns-process-data video --data /workspace/video.mp4

**Expected behavior**

No errors

** Result:
==========
== CUDA ==
==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

/opt/nvidia/nvidia_entrypoint.sh: line 67: exec: ns-process-data: not found

### PR DESCRIPTION
**Pull request by thawn**
On HPC systems, singularity/apptainer is used instead of docker as the container solution.

The current dockerfile does not work under singularity, since nerfstudio is installed under /home/user, which is not accessible when the container is run in singularity/apptainer. The problem is that under singularity, the user inside the container has the same rights as outside the container and thus cannot access the contents of the folder belonging to another user. This makes singularity containers secure to use in a multi-user environment.

The proposed changes install nerfstudio in the system environment, making it available to all users.

I have tested this container with singularity3.11 on an HPC system and it works. The container is available on https://hub.docker.com/repository/docker/thawn/nerfstudio
closes #2952

### CODE REVIEW

**Comment by brentyi** [comment]
Could you comment on the relationship between these changes and #3283? (cc @jkulhanek)

**Comment by thawn** [comment]
@brentyi 
after a cursory look into #3283 it looks to me like that pull request would also solve the issues with apptainer. 
In addition, it adds some nice features like an automatic build action.

Furthermore, #3283 has already been extensively reviewed.

Therefore, I am closing this pull request in favor of #3283.

**Comment by thawn** [comment]
Fingers crossed for getting #3283 merged soon 🤞

**Comment by thawn** [comment]
I am keeping my fork and branch until #3283 has been merged and tested.

**Comment by jkulhanek** [comment]
Sorry, I was on a vacation. Can you try to pull the image compiled from #3283 if it works with apptainer?

**Comment by thawn** [comment]
@jkulhanek thanks for your excellent work on #3283 . I pulled `docker://ghcr.io/nerfstudio-project/nerfstudio:pr-3283` with singularity and it works well 👍

**Pull request closed without merging**
