### PR TITLE
Update metashape_utils.py

### PR DESCRIPTION
**Pull request by henrypearce4D**
Changed the ValueError message when using a camera.xml that contains multiple sensors. Per-frame intrinsics can be defined, the previous message said that they were not supported.

### CODE REVIEW

**Review by brentyi — APPROVED** [review]
Looks correct to me!

**Comment by f-dy** [comment]
I don't understand: the previous message was correct, and it was triggered only when using several camera_model values in the metashape project (eg fisheye + perspective).

The limitation does not come from this utility but from nerfstudio itself, see [here](https://github.com/nerfstudio-project/nerfstudio/blob/43c399e71ead6a9a733e29efa1c5966da3ff4629/docs/quickstart/data_conventions.md?plain=1#LL44C168-L44C210):  "Per-frame `camera_model` is not supported." - which is exactly the sentence I used in the error message.

**Comment by f-dy** [comment]
@henrypearce4D @brentyi I think this should be reverted, as the new message is more confusing.

**Comment by brentyi** [comment]
Yeah, on a re-read the original error message makes sense. @henrypearce4D can you comment/confirm?

**Comment by henrypearce4D** [comment]
@brentyi -
@f-dy Is correct, it can be reverted perhaps with a little clarification added as another user recently mentioned this was a little confusing;

`nerfstudio does not support per-frame camera_model types, only one sensor type can be used. OPENCV, OPENCV_FISHEYE, EQUIRECTANGULAR.`

**Comment by brentyi** [comment]
@henrypearce4D that sounds reasonable to me!

**Pull request merged**
