### PR TITLE
[WIP] Add support for OpenSfM

### PR DESCRIPTION
**Pull request by kevinddchen**

### CODE REVIEW

**Comment by antoinemacia** [comment]
@kevinddchen  not sure if you're still working on this or if pending review: I fixed a typecheck as Im hoping to process some data through your script (thanks!) https://github.com/nerfstudio-project/nerfstudio/pull/1073

**Comment by kevinddchen** [comment]
@antoinemacia I am not working on this at the moment--I hear this script is going through / has gone through a refactor? Either way, this PR will likely be superseded with a different one. I'm just keeping it here for future reference. Maybe someone with more knowledge can chime in here (@akristoffersen ?)

But if you want, you are free to merge into this branch

**Comment by antoinemacia** [comment]
Got it thanks @kevinddchen  - Ill just merge it in to avoid having 2 PR floating on the same subject

Im actually just after processing equirectangulars images I just stitched to use in [your recently merged work](https://github.com/nerfstudio-project/nerfstudio/pull/966), without feeding it into OpenSfM

**Comment by akristoffersen** [comment]
@antoinemacia I'm not sure on what's going to happen with this branch, but yesterday I pushed a branch on alex/open_sfm to merge a newer main commit into this branch. I wasn't able to get it working due to openSfM failing to install, so you're mileage may vary though. 

Feel free to commit to either branch, or make your own off of them though. Originally we were looking at openSfM as an alternative to Colmap, but we'd need to look into it more to be sure.

**Comment by tancik** [comment]
Closing, this is pretty out of date now. If anyone wants to pick it up, feel free to reopen.

**Comment by YuhsiHu** [comment]
I am trying to use the results of OpenSfM instead of COLMAP as input. So I found this issue. Is the development of this feature discontinued?

**Pull request closed without merging**
