### PR TITLE
DNeRF Data Parser

### PR DESCRIPTION
**Pull request by JulianKnodt**
This adds the ability to actually load the D-NeRF dataset, which another PR adds. This technically should be merged after that one, but they are independent. It also mostly is the same as `BlenderDataParserConfig` so I'm not sure if they should be merged together.

### CODE REVIEW

**Comment by tancik** [comment]
I think it is fine to keep it a separate file for now.

**Comment by ethanweber** [comment]
Thanks for your PRs @JulianKnodt! Just wanted to let you know we are currently traveling in Tel Aviv for the conference ECCV so we may be slow to reply for another week. Thanks for making additions to the codebase!

**Comment by JulianKnodt** [comment]
@ethanweber no worries, enjoy Tel Aviv and ECCV!

**Comment by JulianKnodt** [comment]
Assuming you're back from ECCV, let me know what else needs to be updated for this to be merged! If you want me to combine this with the D-NeRF PR I can also do that.

**Review by tancik — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
