### PR TITLE
Add support for more colmap camera models in ns-process-data

### PR DESCRIPTION
**Pull request by jkulhanek**
This PR adds support for more COLMAP camera models.
It addresses this issue: #1438

I was also thinking... perhaps I am missing something, however, isn't the FISHEYE distortion implementation wrong?
The code here: https://github.com/google/nerfies/blob/main/nerfies/camera.py doesn't match the COLMAP's implementation (https://github.com/colmap/colmap/blob/dev/src/base/camera_models.h). The implementation was taken from here: https://github.com/google/nerfies/blob/main/nerfies/camera.py, however, did the original code consider FISHEYE models?

### CODE REVIEW

**Comment by tancik** [comment]
The multinerf code was used as reference. They extend the nerfies code to work with fisheye.https://github.com/google-research/multinerf/blob/main/internal/camera_utils.py
Perhaps it is also incorrect?

**Comment by jkulhanek** [comment]
I was wrong. The math in multinerf is correct.

**Review by tancik — APPROVED** [review]
LGTM. Thanks for adding. Other colmap camera models have been requested a number of times, I'm glad to see them added!

**Comment by jkulhanek** [comment]
This is related: #1276

**Comment by tancik** [comment]
This appears to break processing when depth data isn't included. There is a PR to fix here - https://github.com/nerfstudio-project/nerfstudio/pull/1528

**Comment by jkulhanek** [comment]
I don’t think so. It was definitely broken by PR #1531 (I mentioned it in the PR comments). In this PR I believe I fixed it for the ns-process-data images, but the same bug was also in other places apparently.

**Comment by atonderski** [comment]
> I was wrong. The math in multinerf is correct.

@jkulhanek Would you mind quickly elaborating? I followed down the same rabithole and do not see how the implementations are equivalent. Thanks in advance!

**Comment by jkulhanek** [comment]
The undistort solves the original distortion in normal space. Then try substituting https://github.com/google-research/multinerf/blob/5d4c82831a9b94a87efada2eee6a993d530c4226/internal/camera_utils.py#L585 to the original equations. It should lead to the radial equations if I remember correctly.

**Comment by jkulhanek** [comment]
Consider undistort as a “black box” that solves the original problem. Then work backwards from the substitution

**Comment by atonderski** [comment]
Thanks, appreciate it!

**Pull request merged**
