### PR TITLE
Add option to use Pixel Perfect SFM

### PR DESCRIPTION
**Pull request by pablovela5620**
Added the option to use https://github.com/cvg/pixel-perfect-sfm, when using hloc. Also added deps to docker since its a bit of a pain to install otherwise. I modified the docker-compose file as `dromni/nerfstudio:0.1.18` would need to be updated and I'm guessing that won't be till 0.1.19, I can change back to dromni image when that happens. I'm not sure if it makes a huge difference (with camera optimization enabled) but thought I may be worth a PR.

Let me know your thoughts

### CODE REVIEW

**Comment by f-dy** [comment]
Thanks! that definitely looks like an interesting option!
What did you observe when looking at the results?
Camera optimization may not be able to fully recover from a noisy initialization and may even degrade the results (eg on the synthetic datasets), so I would also compare pixel-perfect without camera optimization to COLMAP with camera optimization.

**Review by tancik — APPROVED** [review]
LGTM, thanks for adding.

**Comment by pablovela5620** [comment]
> Thanks! that definitely looks like an interesting option! What did you observe when looking at the results? Camera optimization may not be able to fully recover from a noisy initialization and may even degrade the results (eg on the synthetic datasets), so I would also compare pixel-perfect without camera optimization to COLMAP with camera optimization.

TBH I didn't find a significant difference, but maybe that's due to the dataset I was using. Would be good to see some more results from others

**Comment by f-dy** [comment]
Did you try *without* camera pose optimization?

**Comment by nkyriazis** [comment]
I can't figure out why the refine_pixsfm option is not exposed through cli (ns-process-data).

**Comment by tancik** [comment]
Are you using the pip package, or the github version?

**Comment by nkyriazis** [comment]
I'm running from the latest image on the docker hub.

**Comment by pablovela5620** [comment]
it should be exposed? does it not show when using the `images` or `videos` argument? Here's what mine shows when I do `ns-process-data images --help`
Screenshot from 2023-03-19 13-56-34

**Comment by pablovela5620** [comment]
> Did you try _without_ camera pose optimization?

I did not, this would be good to try, just have not had the chance as I'm working on bringing in SDF based methods

**Comment by tancik** [comment]
Maybe the confusion is that it isn't exposed for `ns-process-data video`

**Comment by devernay** [comment]
`ns-process-data video` should only extract images from video, is there a chance we could allow both `video` and `images` on the same line, with separate options? Or should `video` automatically inherit from all `images`options?

**Comment by tancik** [comment]
I think `video` should essentially just inherit all of the image options.

**Comment by nkyriazis** [comment]
> it should be exposed? does it not show when using the `images` or `videos` argument? Here's what mine shows when I do `ns-process-data images --help` Screenshot from 2023-03-19 13-56-34

image
image

**Comment by tancik** [comment]
The latest pip package (used in docker) does not have this yet. You need to use the latest github version.

**Comment by nkyriazis** [comment]
Could you identify for me what the missing link is? I see that several things are in place and I'm trying to figure out why my expectation that the parameter should be there is not met.

**Pull request merged**
