### PR TITLE
Forcing setuptools version to 69.5.1 to overcome build error.

### PR DESCRIPTION
**Pull request by aravindhankrishnan**
Using the latest version of setuptools (70.0.0) gives an ImportError on "import packaging". Reverting to 69.5.1 resolves this issue.

### CODE REVIEW

**Comment by maturk** [comment]
does setuptools==69.5.1? I think setuptools<70.0.0 should suffice?

**Comment by aravindhankrishnan** [comment]
69.5.1 is the version previous to 70.0.0.

**Comment by jb-ye** [comment]
Do you have error logs? 

Is this [issue](https://github.com/pypa/setuptools/issues/4414
)?

This PR is a work-around, but I believe this is a high priority bug for setuptools/packaging to fix.

**Comment by aravindhankrishnan** [comment]
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/NVlabs/tiny-cuda-nn.git@v1.6#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn.git (to revision v1.6) to /tmp/pip-req-build-lefhvrzb
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn.git /tmp/pip-req-build-lefhvrzb
  Running command git checkout -q 8e6e242f36dd197134c9b9275a8e5108a8e3af78
  Resolved https://github.com/NVlabs/tiny-cuda-nn.git to commit 8e6e242f36dd197134c9b9275a8e5108a8e3af78
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-lefhvrzb/bindings/torch/setup.py", line 5, in <module>
          from torch.utils.cpp_extension import BuildExtension, CUDAExtension
        File "/home/user/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/user/.local/lib/python3.10/site-packages/pkg_resources/__init__.p
y)
      [end of output]

**Comment by maturk** [comment]
> Do you have error logs?
> 
> Is this [issue](https://github.com/pypa/setuptools/issues/4414)?
> 
> This PR is a work-around, but I believe this is a high priority bug for setuptools/packaging to fix.

yeah I agree, it is quite high priority.

**Comment by abrahamezzeddine** [comment]
> Do you have error logs?
> 
> Is this [issue](https://github.com/pypa/setuptools/issues/4414)?
> 
> This PR is a work-around, but I believe this is a high priority bug for setuptools/packaging to fix.

Please see #3159

**Comment by pradyunsg** [comment]
FYI: https://github.com/pypa/setuptools/issues/4385

**Comment by jakepopham** [comment]
> 69.5.1 is the version previous to 70.0.0.

But using <70 should ensure we get future maintenance updates on version 69.X.X without the breaking changes of 70.

**Comment by jb-ye** [comment]
close as dup of https://github.com/nerfstudio-project/nerfstudio/pull/3268

**Pull request closed without merging**
