### PR TITLE
fixing colmap installation to use apt-get since gdown on the URL unable to download colmap

### PR DESCRIPTION
**Pull request by AntonioMacaronio**
in the demo colab notebook, `gdown` is unable to install `colmap` because the gdrive link is not sharable or not available. 

This issue is also mentioned here:
1. https://github.com/nerfstudio-project/nerfstudio/pull/2787/files
- `!conda install -c conda-forge colmap` will raise a `PackagesNotFoundError`.
2. https://github.com/nerfstudio-project/nerfstudio/issues/2406#issuecomment-1746746583
- the fix mentioned here will also have a `PackagesNotFoundError` and then the runtime always crashes/restarts

To download colmap, using `apt-get` solved these issues and allowed me to process my data in the following cell - it is a quick one-line and it takes about 4minutes 16seconds to install nerfstudio and its dependencies

### CODE REVIEW

**Review by ginazhouhuiwu — COMMENTED** [review]
lgtm

**Comment by brentyi** [comment]
I think that the `apt` version of colmap isn't GPU-accelerated, so maybe still revisiting again before #2787 is merged?

**Comment by ginazhouhuiwu** [comment]
Will definitely do!

**Comment by ginazhouhuiwu** [comment]
I think for now if it patches the issue (which it seem to do), can be merged in main. I personally didn't run into problems with `conda` install so I have to look into it more and see what the discrepancy is.

**Comment by brentyi** [comment]
Sounds good! I think missing GPU support in `colmap` is possibly also fine if it makes the install much easier. We could maybe benchmark.

**Comment by machenmusik** [comment]
I would recommend benchmarking, as my recollection of colmap non-GPU on larger datasets was... significantly slower execution.

**Pull request merged**
