### PR TITLE
Update splatfacto with gsplat 1.0

### PR DESCRIPTION
**Pull request by liruilong940607**
- Pin dependence to `gsplat==1.0.0`
- A few slight improvements on splatfacto model and its data loading, by @kerrj 

This is a hot fix as the `pip install nerfstudio` would be failing currently because of #3197  so we need to bump a version that either pins to `gsplat==1.0.0` or pins to `gsplat <=1.0.0` asap.

### CODE REVIEW

**Review by kerrj — APPROVED** [review]
lgtm!

**Comment by abrahamezzeddine** [comment]
@kerrj @liruilong940607  After the update, I am getting this error now.

Traceback (most recent call last):
  File "C:\Users\husse\.conda\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\husse\.conda\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\husse\.conda\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 4, in <module>
  File "C:\nerf\nerfstudio\nerfstudio\scripts\train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "C:\nerf\nerfstudio\nerfstudio\configs\method_configs.py", line 50, in <module>
    from nerfstudio.engine.trainer import TrainerConfig
  File "C:\nerf\nerfstudio\nerfstudio\engine\trainer.py", line 46, in <module>
    from nerfstudio.viewer.viewer import Viewer as ViewerState
  File "C:\nerf\nerfstudio\nerfstudio\viewer\viewer.py", line 37, in <module>
    from nerfstudio.models.splatfacto import SplatfactoModel
  File "C:\nerf\nerfstudio\nerfstudio\models\splatfacto.py", line 103, in <module>
    def get_viewmat(optimized_camera_to_world):
  File "C:\Users\husse\.conda\envs\nerfstudio\lib\site-packages\torch\__init__.py", line 1705, in fn
    return compile(model,
  File "C:\Users\husse\.conda\envs\nerfstudio\lib\site-packages\torch\__init__.py", line 1723, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
  File "C:\Users\husse\.conda\envs\nerfstudio\lib\site-packages\torch\_dynamo\eval_frame.py", line 583, in optimize
    check_if_dynamo_supported()
  File "C:\Users\husse\.conda\envs\nerfstudio\lib\site-packages\torch\_dynamo\eval_frame.py", line 535, in check_if_dynamo_supported
    raise RuntimeError("Windows not yet supported for torch.compile")
RuntimeError: Windows not yet supported for torch.compile

Any suggestions?

**Comment by liruilong940607** [comment]
@abrahamezzeddine fixed in #3202

**Comment by abrahamezzeddine** [comment]
@liruilong940607  Is it possible to use packed as True with splatfacto? I tried to use it but it says the tensors are not matched if yes. 

Would be nice if I could trade speed vs memory.

**Comment by liruilong940607** [comment]
@abrahamezzeddine This PR is just a quick fix that makes the nerfstudio model compatible with gsplat v1.0. To fully support all functionalities of gsplat v1.0, there are still quite some upgrades need to be done. So please stay tuned! (Contribution is always welcomed!)

**Pull request merged**
