### PR TITLE
Fix parsing of non ascii image names in colmap's images.bin

### PR DESCRIPTION
**Pull request by TamirCohen**
If colmap image file name is non ascii an error will be thrown in the line `current_char.decode("utf-8")` while trying to parse the file `images.bin`
It is thrown because it tries to decode a single byte as `utf-8`, And non ascii chars are represented using more bytes than 1.

My solution proposal is to read all the bytes, and than decode it.
I tested it and it worked OK

### CODE REVIEW

**Review by kerrj — APPROVED** [review]
looks good, also tested on a few datasets and it works thanks!

**Comment by TamirCohen** [comment]
Thanks @kerrj.
Due to an error in the sphynx build I can not merge it (I do not think it is related to my commit).
Should I wait after https://github.com/nerfstudio-project/nerfstudio/pull/3265 is fixed and then merge it?

**Comment by kerrj** [comment]
Could you re-run lint please? the linter was updated along with the np 2.0 patch

**Comment by TamirCohen** [comment]
I reran it and it did not work because there are empy comments in:
https://github.com/nerfstudio-project/nerfstudio/blob/d6df39b70d2e0b444178d23b694989e39d624781/nerfstudio/configs/method_configs.py#L304
https://github.com/nerfstudio-project/nerfstudio/blame/d6df39b70d2e0b444178d23b694989e39d624781/tests/pipelines/test_vanilla_pipeline.py#L41

Should we remove these empty comment in another PR or in this PR?

**Comment by jb-ye** [comment]
Just rebase to the top main should resolve the issue.

**Pull request merged**
