### PR TITLE
expose downscale-factor

### PR DESCRIPTION
**Pull request by machenmusik**
This PR exposes downscale-factor as an adjustable parameter `--pipeline.datamanager.downscale-factor
` to allow experimentation (since it is not exposed / effective via pipeline.datamanager.dataparser)

### CODE REVIEW

**Comment by jkulhanek** [comment]
Is this a shortcut for pipeline.datamanager.dataparser.downscale_factor?

**Comment by machenmusik** [comment]
That is where it should be IMO, but when I try using that with `ns-train nerfacto` it gives errors (doesn't work), thus the datamanager override

**Comment by tancik** [comment]
It should be accessible via `ns-train nerfacto ... nerfstudio-data --downscale-factor 2`.
The base dataparser doesn't require `downscale-factor` to be implemented, so this could fail for some dataparsers, https://github.com/nerfstudio-project/nerfstudio/blob/ef1350bd3627afc515ed86a379ceea676ed5850a/nerfstudio/data/dataparsers/base_dataparser.py#L115-L121

**Comment by machenmusik** [comment]
My recollection is that other dataparsers support it as well, although not required (maybe copied from 
nerfstudio loader), and so this could provide a uniform method to access the parameter.  Perhaps this would not be necessary or useful if nerfstudio-data were default config rather than blender...

Feel free to close if you prefer current methodology.

**Pull request closed without merging**
