### PR TITLE
Fix Discord link in the docs

### PR DESCRIPTION
**Pull request by mackopes**
In the docs [contributing page](https://docs.nerf.studio/en/latest/reference/contributing.html), the discord link seems to be invalid (as reported by Discord)
image

However, the one in the README.md seems to work. So I copypasted the same link to the docs, too.

### CODE REVIEW

**Review by tancik — APPROVED** [review]
Thanks

**Comment by gowriaddepalli** [comment]
@tancik https://discord.gg/uMbNqcraFc i am trying to access this discord link and i am still getting the same error message as above. Please let me know how to join discord channel. Thanks.

**Comment by tancik** [comment]
That's odd, the link still works for me? Try this new link https://discord.gg/RyVk6w5WWP

**Comment by gowriaddepalli** [comment]
This one works for me thanks.

**Pull request merged**
