### PR TITLE
Adding support for PairPixelSampler and PatchPixelSampler masks

### PR DESCRIPTION
**Pull request by ethanweber**
PR to address Issue #2304. This PR adds mask support for the PairPixelSampler by using an erode function.

### CODE REVIEW

**Comment by machenmusik** [comment]
Thanks - even with `--pipeline.datamanager.masks-on-gpu True` it is slow, so may take a while to provide feedback.

**Comment by machenmusik** [comment]
It works with masked datasets (which unfortunately I can't share) -- although hard to say whether depth-nerfacto improves significantly over (non-depth) nerfacto so far, it is obviously better than failing with NonImplementedError.

**Review by machenmusik — APPROVED** [review]

**Comment by machenmusik** [comment]
Doing a quick A-B between defaults of depth-nerfacto and nerfacto using generated depth, my quick take is that depth-nerfacto avoids ghosting, but seems less sharp.  Currently I am wondering whether the default resolution for Zoe depth image generation is too low, and/or the default parameters no longer match.

**Comment by ethanweber** [comment]
I also added support for patches.

**Review by AdamRashid96 — COMMENTED** [review]
This all LGTM! I don't have data with masks to test it though so if @machenmusik could try the patch sampler with masks to see if it works that would be great.

**Comment by machenmusik** [comment]
There is a mustard dataset referenced in a few of the older PRs around masks... anyone recall which methods are currently using patch pixel sampling to try with?

**Comment by machenmusik** [comment]
Not in position to test the patch sampling pieces at the moment, but it can't be worse than NotImplementedError failure, so will merge.

**Pull request merged**
