### PR TITLE
Upgraded Polycam Error

### PR DESCRIPTION
**Pull request by Mozhganhd**
Fixed directory path issue after upgrading Polycam app.
This will work for the extracted data from the upgraded Polycam app.

### CODE REVIEW

**Comment by jb-ye** [comment]
can you comment which version of polycam starts this new extraction behavior in the code / [doc](https://github.com/nerfstudio-project/nerfstudio/blob/main/docs/quickstart/custom_dataset.md?plain=1#L163)?

**Comment by Mozhganhd** [comment]
If I’m not mistaken, it should be after 3.4.7 as they improved export options in that version and next versions.
IMG_6243

**Comment by kerrj** [comment]
Hm I thought I had fixed this already a month ago or so and it worked for me, what phone are you using polycam with?

**Comment by kerrj** [comment]
Any update on this? @Mozhganhd

**Comment by kerrj** [comment]
closing due to inactivity, feel free to reopen

**Pull request closed without merging**
