### PR TITLE
feat(ci): switch caching to `actions/setup-python@v4`

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Changes made by this PR can be summarized as follows:

- Set the `cache` and `cache-dependency-path` argument of `actions/setup-python` to enable `pip` caching.
- Delete the redundant `actions/cache@v2` step.

### CODE REVIEW

**Comment by tancik** [comment]
Im a bit unfamiliar with how this caching works under the hood. I've rerun it a few times (so I think it is using the cached version) and it seems to average ~4min. Other runs of `Core Tests` seems to be ~1-1.5 min quicker. Any ideas why this would be the case?

image

image

**Comment by SauravMaheshkar** [comment]
@tancik this is interesting. I don't know why this is the case. I had a look at the older versions of "Core Tests" and it seems like (setup python + caching + dependency installation) does happen quicker compared to (setup python with caching + dependency installation).

**Comment by SauravMaheshkar** [comment]
Maybe the slower installation times could be because of "fetching" the packages from a cache.

**Comment by tancik** [comment]
Is there an advantage to using this cache if the other method is faster? I ideally don't want to pay for more github action minutes.

**Comment by SauravMaheshkar** [comment]
None that I am aware of, it just seemed best practice to cache the dependencies. 

> The action has built-in functionality for caching and restoring dependencies. It uses [toolkit/cache](https://github.com/actions/toolkit/tree/main/packages/cache) under the hood for caching dependencies but requires less configuration settings. ([_From the "Caching package dependencies" section of setup-python README_](https://github.com/actions/setup-python#caching-packages-dependencies))

If it indeed is slower than just using `actions/cache` which is what the cache implementation is based on then adding the cache parameter might not be ideal.

**Comment by SauravMaheshkar** [comment]
@tancik How about I close this PR at the moment ? and maybe in the future we can get back to it if there are visible benefits.

**Comment by tancik** [comment]
yea, sounds good. Sorry for not having more to add.

**Pull request closed without merging**
