### PR TITLE
Fix the background color bug when exporting video with the "random" background option

### PR DESCRIPTION
**Pull request by KevinXu02**
Set default bg to viser color in gs to fix strange bg color in rendering.

### CODE REVIEW

**Comment by bobye** [comment]
Training with random background is a feature not a bug.

**Comment by KevinXu02** [comment]
> Training with random background is a feature not a bug.

Hi! This modification won’t affect training, the background is still randomly picked . It only change the background color when exporting video.

**Comment by jb-ye** [comment]
I see. But the code here is quite confusing. Could you add some comments explaining the effect of setting this to a magic value?

**Comment by KevinXu02** [comment]
> I see. But the code here is quite confusing. Could you add some comments explaining the effect of setting this to a magic value?

Oh, the value is just the same background color as the one for viser. The training background logic is defined seperately, so this value would only work when it is not in training.

**Comment by jb-ye** [comment]
Yeah, I know. That's what I suggested for adding those comments above the line of change.

**Comment by KevinXu02** [comment]
> Yeah, I know. That's what I suggested for adding those comments above the line of change.

Comments added. Thank you for your suggestion.

**Comment by kerrj** [comment]
This works as a patch, but what might be a more permanent fix is to propagate the background color set in viser into render `crop_data` so that [this line ](https://github.com/nerfstudio-project/nerfstudio/blob/1bc5b424b41d889ed845f16e55bd7631b3175622/nerfstudio/scripts/render.py#L186)gets called even if the scene isn't cropped

**Review by kerrj — APPROVED** [review]
fixes #2815 , but might want to revisit how background is handled in the render `crop_data` so that users can define a background even if the 'crop scene' option is not selected

**Pull request merged**
