### PR TITLE
fix notebook, box drawing

### PR DESCRIPTION
**Pull request by 3a1b2c3**
some camera parameter in the notebooks need to be float, not sure how to get rid of reformatting scientific notation....

### CODE REVIEW

**Comment by 3a1b2c3** [comment]
sure, thanks for letting me know

**Comment by tancik** [comment]
Hmm, it still looks like the output's aren't being saved. Perhaps it is a setting in your IDE?

**Comment by 3a1b2c3** [comment]
i check again, i am using vscode

**Comment by tancik** [comment]
I am also used vscode. I tried building your docs locally (`python scripts/docs/build_docs.py --clean-cache`) and it is also missing the plots. When I rerun the cells, it adds extra information to the notebook that seems to not be added when you run it, it is a lot of code, but this is the start of it,
```
 "data": {
      "text/html": [
       "        <script type=\"text/javascript\">\n",
       "        window.PlotlyConfig = {MathJaxConfig: 'local'};\n",
       "        if (window.MathJax) {MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n",
       "        if (typeof require !== 'undefined') {\n",
       "        require.undef(\"plotly\");\n",
       "        define('plotly', function(require, exports, module) {\n",
```

I'm not sure why they would end up being different. If you haven'y already, can you try `pip install -e .[docs]` maybe the `myst-nb` or `nbconvert` changes how this works.

**Comment by 3a1b2c3** [comment]
maybe another windows mystery. maybe quicker close this pr and just do the changes elsewhere?
image

**Comment by tancik** [comment]
If you give me access to your repo, I can also just run it and save the notebooks with the correct metadata.

**Comment by 3a1b2c3** [comment]
Done, thanks. Sorry its so complicated

**Review by tancik — APPROVED** [review]
Thanks for bearing with this!

**Pull request merged**
