### PR TITLE
Allow use of black or white background in Nerfacto models

### PR DESCRIPTION
**Pull request by iSach**
For synthetic data like the Blender dataset, the background is white and thus it is more appropriate to use a white value for untrained areas, as done in Instant-NGP. 

Although already partly implemented, the option was simply not allowed.

- I cleaned the use of the color for the background to be consistent between methods.
- I allowed white and black in Nerfacto and NerfPlayer-Nerfacto
- I updated the blender benchmark script to use the white background in addition to the other methods mentioned in issue #806.

On the Blender benchmark, losses are obviously lower, and seem to converge faster.
image
image

### CODE REVIEW

**Comment by iSach** [comment]
It reduces artifacts on the object for blender results but for some reason adds more artifacts around the object, which it is exactly what it is supposed to fix.

However, it greatly helps quantitavely. For the Hot Dog scene, the PSNR goes from 19 to 27.

image
image

**Comment by iSach** [comment]
Also, surprisingly, it does not seem sufficient whereas for Instant-NGP, this single option suffices to fix the training. Nerfacto for some reason requires additional tuning (especially modifying the far/near plane parameters) that Instant-NGP does not require.

Does anybody have an idea why?

**Comment by iSach** [comment]
A last note: maybe it could be interesting or useful to some data to allow the use of any color (or at least all colors in the "COLORS_DICT"). It would require no change than allowing these color strings in the method parameters.

**Review by tancik — APPROVED** [review]
LGTM, thanks for adding

**Comment by tancik** [comment]
For better blender results you probably want to disable scene contraction, and use a uniform sampling for the first step of the proposal sampler (instead of piecewise sampling).

**Comment by tancik** [comment]
To test for lint errors locally, run `ns-dev-test`

**Comment by iSach** [comment]
> For better blender results you probably want to disable scene contraction, and use a uniform sampling for the first step of the proposal sampler (instead of piecewise sampling).

If I'm not wrong (sorry for that, still new and navigating the whole code), it's not possible with current parameters of the model right? Just to know, if so it could be a good idea to add them and I might look at it, in order to better support synthetic data.

**Comment by tancik** [comment]
Feel free to add the sampler parameter to the model.

**Comment by sam598** [comment]
> It reduces artifacts on the object for blender results but for some reason adds more artifacts around the object, which it is exactly what it is supposed to fix.
> 
> However, it greatly helps quantitavely. For the Hot Dog scene, the PSNR goes from 19 to 27.
> 
> image image

The artifacts are happening because you can't just train a solid color for a transparent object. You need to use alpha/transparency to control density.

**Comment by iSach** [comment]
considering the way the background color gets added to the total color with (1-accumulated weights) * background color, shouldn’t it train it to have zero density to be close to the background color? I don’t see alpha being used right?Le 23 mars 2023 à 22:52, sam598 ***@***.***> a écrit :﻿

It reduces artifacts on the object for blender results but for some reason adds more artifacts around the object, which it is exactly what it is supposed to fix.
However, it greatly helps quantitavely. For the Hot Dog scene, the PSNR goes from 19 to 27.
 

The artifacts are happening because you can't just train a solid color for a transparent object. You need to use alpha/transparency to control density.

**Comment by sam598** [comment]
alpha is an explicit value. background color is ambiguous.

**Pull request merged**
