### PR TITLE
tag exported ply files

### PR DESCRIPTION
**Pull request by simonbethke**
I would like to write the keyword "Nerfstudio" into exported ply files so other software can compensate for the 90° rotation Nerfstudio applies to the data (it doesn't really matter what is the standard and what isn't. It is generally helpful, to have the possibility to know who wrote a file)

### CODE REVIEW

**Comment by brentyi** [comment]
Would it make sense to include the nerfstudio version?

I think it can be read via:
```
from importlib.metadata import version
nerfstudio_version = version("nerfstudio")
```

**Comment by simonbethke** [comment]
That would totally make sense. I was not aware of any way to read it :)

**Comment by simonbethke** [comment]
Examples: 

comment Generated by Nerfstudio 1.0
comment Vertical Axis: z

comment Generated by SuperSplat 1.0
comment Vertical Axis: y

**Review by brentyi — APPROVED** [review]
Looks great, thanks @simonbethke!

**Pull request merged**
