### PR TITLE
fix crash when both mask and downscale_factor are set

### PR DESCRIPTION
**Pull request by jinhwanlazy**
Splatfacto crashes when mask is exist and num_downscale > 0, because downscale has not been applied to mask.

### CODE REVIEW

**Comment by jb-ye** [comment]
Thanks for the catch. It looks good to me. 

May I ask when you found `num_downscale > 0` useful? I set it to zero because I didn't observe any benefits of that and the official Inria GS doesn't do it either.

**Comment by jinhwanlazy** [comment]
I found no big difference in the end results, but it makes first training iterations sigificantly faster. So I think it like, why not?

**Comment by jb-ye** [comment]
> I found no big difference in the end results, but it makes first training iterations sigificantly faster. So I think it like, why not?
Okay, I agree this is a bug to be fixed.

**Review by kerrj — APPROVED** [review]
thanks!

**Pull request merged**
