### PR TITLE
Fix depth-supervised nerf when using z-buffer depth.

### PR DESCRIPTION
**Pull request by jeffreyhuparallel**
When training depth-nerfacto with two images from the Replica Dataset, the result appears to poorly align the two ground truth depth maps. This PR fixes the issue.

rgb_0
rgb_180

Script:
```
ns-train depth-nerfacto \
    --data data/nerfstudio/replica_mini/ \
    --pipeline.model.depth-loss-mult 0.01 \
    --vis tensorboard \
    nerfstudio-data \
    --auto-scale-poses False \
    --center-poses False \
    --train-split-percentage 0.5
```

Before:
image
image

After:
image
image

### CODE REVIEW

**Review by tancik — APPROVED** [review]
Results look good. Thanks for the fix.

**Comment by matsuren** [comment]
@jeffreyhuparallel 
Thank you for your great PR!
I'm not sure if this is proper place to ask question but how did you generate dataset from Replica dataset?
You used data by running
`ns-download-data sdfstudio --dataset-name replica`
or you extract images and depths from [Replica dataset](https://github.com/facebookresearch/Replica-Dataset) using something like [habitat-sim](https://github.com/facebookresearch/habitat-sim)?

**Comment by jeffreyhuparallel** [comment]
I used the pre-rendered Replica data provided by semantic-nerf. 
https://github.com/Harry-Zhi/semantic_nerf

**Comment by matsuren** [comment]
Thank you! I really appreciate it!

**Pull request merged**
