### PR TITLE
Allow masks with instant ngp dataparser

### PR DESCRIPTION
**Pull request by nepfaff**
### Changes
- Allow using masks with the `instant-ngp-dataloader`
- Move the entire dataset to the GPU when using masks. I feel like this is a reasonable compromise (see [here](https://github.com/nerfstudio-project/nerfstudio/issues/1465))

### CODE REVIEW

**Comment by tancik** [comment]
This looks like a fine compromise to me. Curious to get feedback from @machenmusik since he has thought about this a bit.

**Comment by machenmusik** [comment]
Personally I think this approach is reasonable as well, just two things
- can this be done more generally, and not just to individual methods?
- how does this interact, if at all, with #1730?

**Comment by machenmusik** [comment]
If this makes masks work for ingp and nerfacto (maybe even semantic-nerfw and others?) then personally, I think we should merge

**Comment by nepfaff** [comment]
> does this work more generally

We would need to add the same lines to every dataparser to make it work for that parser. There isn't a clean way around this without some refactoring. 

> how does this interact, if at all, with https://github.com/nerfstudio-project/nerfstudio/pull/1730?

It affects it in a way that this PR refactors this logic. We could keep this logic there, with an additional check of whether "mask" is already in  `exclude_batch_keys_from_device`. It would be cleaner to set `exclude_batch_keys_from_device` at a single place though, so I would add a similar check to where this variable is initialized (multiple places).

**Comment by nepfaff** [comment]
The downside of this approach is that it is still easy to run out of GPU memory for decently large datasets as we are now loading all masks and images into GPU memory. However, not loading masks into the GPU leads to `nerfacto` taking 2h instead of 20min for the default iterations on my machine.

At a minimum, we should make sure that masks and images are on the same device to avoid an exception. This is not the case on master where masks are always loaded into GPU memory, even if images are not.

**Comment by machenmusik** [comment]
Thanks.  If there were an overall policy setting (favor speed, favor min GPU mem) we might want to respect that here (images/masks both the GPU, or not, depending).  But I don't think there is one, and this is better than the earlier change which was reverted.

**Comment by nepfaff** [comment]
> Is there a dataset to check this with after #1809 ?

I don't think this is related, as this PR modified the `instant-ngp` models but not the dataparser, which is model-agnostic. I mainly use this dataparser with `nerfacto`, as I wrote my data pre-processing pipeline for `instantNGP`.

Hence, training any model with data from this dataparser should be sufficient for testing. Should I share some results?

**Comment by machenmusik** [comment]
> Hence, training any model with data from this dataparser should be sufficient for testing. Should I share some results?

That would be great, assuming they are good then I think we can merge.

**Comment by nepfaff** [comment]
I rebased on master and trained on synthetic data of the YCB mustard bottle with masks:
`ns-train nerfacto --vis viewer+wandb instant-ngp-data --data data/mustard`. Maybe I shouldn't have pushed the rebase due to the checks...

Training took around 20min, and the results clearly show the effect of the masks. Noting that this is not necessarily the intended use case of the current masking implementation :)

image

Textured TSDF mesh:
nerfstudio_mustard_nerfacto_w_masks_tsdf_mesh

Are there any other results/ metrics that would be useful?

**Comment by machenmusik** [comment]
LGTM, thanks!

**Comment by Tao-11-chen** [comment]
Why don't you put the sampled indices from GPU to CPU which is both fast and memory efficient. #1819

**Pull request merged**
