### PR TITLE
Update splatfacto.py

### PR DESCRIPTION
**Pull request by Harr7y**
Shape error: The shape of batch['mask'] is [H, W, 1], not[H, W]

### CODE REVIEW

**Comment by brentyi** [comment]
Thanks for the fix!

Just to confirm: what kind of data are you getting HxWx1 masks from? Do you know where in the code these are generated?

It looks like this error is my fault; I added the assertion in https://github.com/nerfstudio-project/nerfstudio/pull/2785, where I'm also creating HxW masks.

cc also @f-dy

**Comment by f-dy** [comment]
I haven't tested the latest mask changes yet (we'll be doing it soon)

**Comment by Harr7y** [comment]
> Thanks for the fix!
> 
> Just to confirm: what kind of data are you getting HxWx1 masks from? Do you know where in the code these are generated?
> 
> It looks like this error is my fault; I added the assertion in #2785, where I'm also creating HxW masks.
> 
> cc also @f-dy

I used the bear data mentioned in nerf2nerf. The mask is generated by myself, a picture with a black center and white sides.
I used the **full_images_datamanager**, and I think the code used for generating the mask should at https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/utils/data_utils.py#L25.

**Comment by Tao-11-chen** [comment]
Hi, the same situation for me, it should be merged.

**Review by kerrj — APPROVED** [review]
thank you! @brentyi it looks like the rest of the repo expects HxWx1, so we should probably change aria to be consistent with that. see https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/utils/data_utils.py#L25

**Pull request merged**
