### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by Zunhammer**
Added a Dockerfile to build docker image including all dependencies and nerfstudio itself.
Added description on how to use the docker image into the Readme.

### CODE REVIEW

**Comment by tancik** [comment]
Sorry for the delayed response (holiday), but this is great! There have been many request for Docker support. My only comment is to move the main docker documentation to - https://github.com/nerfstudio-project/nerfstudio/blob/main/docs/quickstart/installation.md
And then point to this in the `README.md` for interested readers. We want to keep the readme a bit more streamlined.

**Comment by Zunhammer** [comment]
I updated the description and moved it to the docs/quickstart/installation.md file as requested.

**Review by tancik — APPROVED** [review]
LGTM, thanks for adding the docker!

**Comment by ethanweber** [comment]
This is so great!! Thanks @Zunhammer! 🥳

**Pull request merged**
