### PR TITLE
When generating depth images, use torch_compile with ZoeDepth for compatibility

### PR DESCRIPTION
**Pull request by machenmusik**
(for systems needing https://github.com/nerfstudio-project/nerfstudio/pull/1982
e.g. Windows)

### CODE REVIEW

**Comment by machenmusik** [comment]
(not sure what's up with the Pyright complaints, given the small changes)

**Comment by machenmusik** [comment]
Runtime errors encountered; may need to redo.

**Comment by machenmusik** [comment]
Previously the compatibility utility torch.compile worked for functions, but not for modules as torch.compile was originally employed here.  (See https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html for usage.)

**Comment by machenmusik** [comment]
Pyright failure is not a functional issue, see https://github.com/pytorch/pytorch/issues/81462 for more details.

**Comment by machenmusik** [comment]
Related to #2305 @ethanweber if you want to sanity check.
(See https://github.com/nerfstudio-project/nerfstudio/pull/2305#issuecomment-1666067515)

**Comment by machenmusik** [comment]
(Made Pyright happy.)

**Comment by machenmusik** [comment]
(readthedocs check is stuck, 404 details, not sure how to re-run)

**Review by tancik — APPROVED** [review]
LGTM

**Pull request merged**
