### PR TITLE
Camera Label Hiding

### PR DESCRIPTION
**Pull request by mcallisterdavid**
Fix for #567. This is the least janky way I found to do this

cameraLabelHiding

### CODE REVIEW

**Comment by tancik** [comment]
I just tried this here - https://viewer.nerf.studio/versions/branch/davidm-camera-name-hiding/
It doesn't seem to be working?

**Comment by mcallisterdavid** [comment]
> I just tried this here - https://viewer.nerf.studio/versions/branch/davidm-camera-name-hiding/
> It doesn't seem to be working?

Oh I moved away from that branch and thought I deleted it lol. Here's the right one [https://viewer.nerf.studio/versions/branch/davidm-viewier-camera-name-hiding/](https://viewer.nerf.studio/versions/branch/davidm-viewier-camera-name-hiding/)

**Comment by tancik** [comment]
Ahh gotcha. Is clicking the "hide scene" button at the top using different logic?

**Comment by mcallisterdavid** [comment]
> Ahh gotcha. Is clicking the "hide scene" button at the top using different logic?

Not sure, I could check. It seems to be working for me

**Comment by tancik** [comment]
This is what I see
image
image

**Comment by mcallisterdavid** [comment]
> This is what I see
> image
> image

Gotcha I can repro, I'll look into it

**Comment by mcallisterdavid** [comment]
Just added the hide scene logic @tancik

**Review by tancik — APPROVED** [review]
Great! LGTM

**Pull request merged**
