### PR TITLE
Migrate to viser viewer

### PR DESCRIPTION
**Pull request by tancik**

### CODE REVIEW

**Comment by machenmusik** [comment]
(#2542 should probably be fixed before fully switching over)

**Comment by brentyi** [comment]
I think we're ready to move forward with this!

Just need to:
- [ ] Account for the URL change in the Colab (relate problem: https://github.com/nerfstudio-project/nerfstudio/issues/2688)
- [ ] Resolve the merge conflicts 🙃

**Review by kerrj — APPROVED** [review]
LGTM! tested nerfacto for rendering, exporting guis and splatting for rendering.

**Comment by smart4654154** [comment]
thank you very much
The viewer is built on Viser using ThreeJS and packaged into a ReactJS application. This client viewer application will connect via a websocket to a server running on your machine.
I want to control the display range. I would like to ask how this project achieves mouse wheel scaling, left mouse button or keyboard up, down, left and right keys to control rotation, and right mouse button or WASD keys to control position movement.
(https://github.com/nerfstudio-project/nerfstudio/issues/2980)
I think I should modify the scene.jsx file in \ erfstudio \ viewer_legacy \ app. But my modifications are invalid. Even if I delete the \ nerfstudio \ viewer_legacy \ app file, the viewer and viewer_legacy can still run normally
image

Can you tell me the correct file address so that I can modify it.thank you

**Pull request merged**
