### PR TITLE
Add Comet Logging 

### PR DESCRIPTION
**Pull request by sherpan**
This Pull Request aims to Add Comet as a Logging/Experiment Management Tool. 

I created a [Colab](https://colab.research.google.com/drive/1RqIIr9feGBymPXyOQ1PgBih5w3ErHdza#scrollTo=9oyLHl8QfYwP) to test out this feature! 

Let me know if you guys have any questions! Happy to help

### CODE REVIEW

**Comment by sherpan** [comment]
@jkulhanek im confused to as to why the pyright test is breaking? Its saying errors on files i didn't touch?

**Comment by brentyi** [comment]
Those look like warnings; there's only one error on `trainer.py`!

**Comment by sherpan** [comment]
Ah thanks for catch @brentyi!

**Review by tancik — APPROVED** [review]
LGTM

**Comment by sherpan** [comment]
Thanks so much @tancik! 

Just curious when will this feature be available in your next release? What's your release cadence?

**Comment by tancik** [comment]
We don't have any defined release cadence, probably within the next few weeks.

**Pull request merged**
