### PR TITLE
create rays on device when rendering

### PR DESCRIPTION
**Pull request by zmurez**
When using `traj=="filename"` `camera_ray_bundle` is generated on the cpu and then moved to the gpu which can be slow.

### CODE REVIEW

**Review by tancik — APPROVED** [review]
Nice! I get ~6% speedup

**Comment by zmurez** [comment]
I think it depends on utilization/hardware... I got no speed up when running render on a server by itself. But when running 8 copies in parallel on the server (1 per gpu), the cpu became the bottleneck and I got 10x speedup after.

**Comment by tancik** [comment]
Feel free to merge

**Comment by zmurez** [comment]
> Feel free to merge

I don't have merge access.

**Comment by tancik** [comment]
> I don't have merge access.

I merged for now. Sent you a new invite.

**Pull request merged**
