### PR TITLE
Bug fixes on Instant NGP dataparser

### PR DESCRIPTION
**Pull request by akristoffersen**

### CODE REVIEW

**Review by tancik — APPROVED** [review]
Nice! Thanks for the update!

**Comment by belkahorry** [comment]
May i ask how to use Instant NGP dataparser correctly?
I've run `ns-train nerfacto instant-ngp-data --data .` and got this error:
```
Traceback (most recent call last):
  File "/home/horry/anaconda3/envs/torch/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/horry/Nerf/nerfstudio/scripts/train.py", line 248, in entrypoint
    main(
  File "/home/horry/Nerf/nerfstudio/scripts/train.py", line 234, in main
    launch(
  File "/home/horry/Nerf/nerfstudio/scripts/train.py", line 173, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/horry/Nerf/nerfstudio/scripts/train.py", line 87, in train_loop
    trainer.setup()
  File "/home/horry/Nerf/nerfstudio/nerfstudio/engine/trainer.py", line 115, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/horry/Nerf/nerfstudio/nerfstudio/configs/base_config.py", line 66, in setup
    return self._target(self, **kwargs)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 221, in __init__
    self.datamanager: VanillaDataManager = config.datamanager.setup(
  File "/home/horry/Nerf/nerfstudio/nerfstudio/configs/base_config.py", line 66, in setup
    return self._target(self, **kwargs)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 310, in __init__
    self.train_dataset = self.create_train_dataset()
  File "/home/horry/Nerf/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 317, in create_train_dataset
    dataparser_outputs=self.dataparser.get_dataparser_outputs(split="train"),
  File "/home/horry/Nerf/nerfstudio/nerfstudio/data/dataparsers/base_dataparser.py", line 116, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split)
  File "/home/horry/Nerf/nerfstudio/nerfstudio/data/dataparsers/instant_ngp_dataparser.py", line 87, in _generate_dataparser_outputs
    k1=float(meta["k1"]), k2=float(meta["k2"]), p1=float(meta["p1"]), p2=float(meta["p2"])
KeyError: 'k1'
```
This is part of my Transform_train.json:
```
{
  "fl_x": 2839.752793988524,
  "fl_y": 2834.7959897664127,
  "cx": 1879.5,
  "cy": 1058.5,
  "w": 3759.0,
  "h": 2117.0,
  "camera_model": "OPENCV",
  "k1": 0,
  "k2": 0,
  "p1": 0,
  "p2": 0,
  "frames": [
    {
      "file_path": "./images/PXL_20221108_035830902.jpg",
      "transform_matrix": [
        [
          0.9568287584342978,
          0.102107554042625,
          0.27212639405455996,
          1.8505288741135475
        ],
        [
          0.28775550514270953,
          -0.20093402597082113,
          -0.9363878931656534,
          -3.389378074155285
        ],
        [
          -0.04093282547596688,
          0.9742687332144342,
          -0.2216414653892879,
          0.23946123288269242
        ],
        [
          0.0,
          0.0,
          0.0,
          1.0
        ]
      ]
    },
    ....
  ]
}
```

**Comment by akristoffersen** [comment]
Hi, this is strange, the transforms.json definitely has the k1 params, so I'm not sure exactly why it would throw that error. Could you try using an absolute path for --data?

**Comment by belkahorry** [comment]
My fault, i followed mipnerf format filename but ran nerfacto.

**Pull request merged**
